### ISSUE TITLE
Password protected Videos

### ISSUE THREAD

**Issue by amster93** [Vilagamer999/Bulk-Private-Vimeo-Downloader#1]
Hey any chance you can add the function to download password protected videos? password would be next to the URL. --video-password is the yt_dlp_option

**Comment by Vilagamer999** [comment]
Done :)
Simply add `::` after each video link followed by the password in `vimeo_links.txt` like so `https://vimeo.com/12345678::PASSWORD`

`vimeo_links.txt` should look something like this:


https://vimeo.com/123::PASSWORD

https://vimeo.com/45678

https://vimeo.com/12345

https://vimeo.com/789

https://vimeo.com/456789::PASSWORD

https://vimeo.com/345678::PASSWORD

etc.
